apiVersion: v1
kind: Service
metadata:
  name: "{{ include "noria.fullname" . }}-server-headless"
  labels:
{{ include "noria.labels" . | indent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 6033
      targetPort: noria
      name: noria
    - port: 42719
      targetPort: worker
      name: worker
    - port: 39767
      targetPort: domain
      name: domain
    - port: 34391
      targetPort: read
      name: read
  selector:
    app.kubernetes.io/name: {{ include "noria.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
