apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "noria.fullname" . }}-server
  labels:
{{ include "noria.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "noria.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: "{{ include "noria.fullname" . }}-server-headless"
  replicas: {{ .Values.server.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "noria.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        # TODO: actually check that zk is up
        - name: sleep
          image: debian:stretch
          command:
            - sleep
            - "100"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
          command:
            - cargo
            - run
            - --manifest-path
            - noria/Cargo.toml
            - --bin
            - noria-server
            - --
            - --deployment
            - demo
            # TODO: use helper-tpl to turn this into a template
            -  --zookeeper
            - noria-zookeeper-headless:2181
            # TODO: quorum should depend on # of replicas
            - --quorum
            - "2"
            # We need to specify the exact Pod address so that other noria servers can communicate
            - --address
            - "$(POD_IP)"
            - --log-dir
            - /var/lib/noria
            - --verbose
          ports:
            # TODO: check whether these are more required ports
            - containerPort: 6033
              name: noria
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
{{- toYaml .Values.server.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/noria
              name: logs
  volumeClaimTemplates:
    - metadata:
        name: logs
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.server.persistence.size | quote }}
